### ISSUE TITLE
Using Lookup without LookupColumn attribute in model

### ISSUE THREAD

**Issue by dnataraj** [NonFactors/MVC6.Lookup.Web#1]
Hi!

We have a question for you. We have an extensive model, that is shared across many subsystems. We would prefer not to decorate the model classes with [LookupColumn], but rather replace this (if possible) with a method in the equivalent of PeopleLookup (from your examples) - since our view application is just a simple "backoffice" function. Is this in anyway possible? Many thanks.

--deepak

**Comment by Muchiachio** [comment]
Yes you will just need to add column by hand, preferably in lookup constructor like so. Your column key should be equal to property name, to get default lookup to work.
```C#
public class PeopleLookup : MvcLookup<PersonModel>
{
    public PeopleLookup()
    {
        // Columns should already be empty, because you don't have any attributes on your model
        Columns.Add("Name", "Name header");
        Columns.Add("Age", "Age header");
    }
}
```
