### ISSUE TITLE
Does it support local (client) data sources?

### ISSUE THREAD

**Issue by vcaraulean** [NonFactors/MVC6.Lookup.Web#3]
I'm in a quest for a nicer experience for user and I got already a list of items in my model. 
Can I make it easily picked up by Autocomplete, without going to the server and implementing full lookup api/convention? 
And in some places we'll be using server side filtering. So looking with same component to cover both cases...

Thanks

**Comment by Muchiachio** [comment]
Currently no, I'm thinking about supporting dropdown lists from the same source, but I guess that's still not what you are looking for.

How would you image it working? I can only think of loading data directly from the lookup class and injecting it to html from the start (similarly how dropdown does it).

**Comment by Muchiachio** [comment]
ANy example you could give @vcaraulean? :)
