### ISSUE TITLE
control size of input box and font and dialog box

### ISSUE THREAD

**Issue by Ratn007** [NonFactors/MVC6.Lookup.Web#6]
Hello sir, i am using adminlte theme for frontend. when i use lookup up control then size of fonts and dialog box decrease. how can i increase size of fonts of table, input box height and dialog box size and fonts
![add](https://user-images.githubusercontent.com/47474810/69625296-4e09d100-106c-11ea-9ebb-4f7cb25a430b.jpg)

**Comment by Ratn007** [comment]
![dialobox](https://user-images.githubusercontent.com/47474810/69625480-a6d96980-106c-11ea-982a-060d951226d0.jpg)
 this is dialog box size , sir i had followed your instructions

**Comment by Muchiachio** [comment]
You can change styling through css.

**Comment by Ratn007** [comment]
can you please marked classes where should i change

**Comment by Muchiachio** [comment]
You can find affected classes in F12. Ff you can't do that I would recommend not using this library.

**Comment by Ratn007** [comment]
thank you very much sir, i did it. It helped me a lot.
